name: ARQMS
description: An app to configure and manage your arqms devices.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Code Generators
  json_annotation: ^4.4.0
  package_info_plus: ^1.3.0

  # Internalization
  intl: ^0.17.0

  # Ui
  hooks_riverpod: ^1.0.3
  jdenticon_dart: 2.0.0
  flutter_svg: ^1.0.3

  # Services
  mqtt5_client: ^3.1.3
  parse_server_sdk_flutter: ^3.1.0
  google_sign_in: ^5.2.3
  googleapis: ^7.0.0
  googleapis_auth: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generators
  build_runner: ^2.1.2
  json_serializable: ^6.1.4

  # The lint set provided by the package is activated in the `analysis_options.yaml`
  flutter_lints: ^1.0.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/i18n/de.json
    - assets/google-logo.png
    - assets/connect_cable.gif
